#!/bin/bash
#Raspberry Pi post installation script
#usage: curl -Lo- https://raw.githubusercontent.com/yves-ledermann/rpi-postinstall/master/rpi_run | bash

# Original Version from http://github.com/dakb/rpi/

#variables
packages="htop dnsutils nano sudo rpi-update raspi-config usbutils dosfstools"
services="hciuart.service bluetooth.service avahi-daemon.service fake-hwclock.service"
temp="https://raw.githubusercontent.com/yves-ledermann/rpi-postinstall/master/temp"
timeserver="ntp.metas.ch"
APT_PROXY_IP="10.11.22.60"
APT_PROXY_PORT="3142"

#temperature script
wget -q $temp -P /usr/bin/
chmod u+x /usr/bin/temp
echo "[+]temperature script downloaded and ready"

#set correct timezone
timedatectl set-timezone Europe/Zurich >/dev/null
echo "[i]timezone set to Europe/Zurich"

#nano color syntax
echo 'include "/usr/share/nano/nanorc.nanorc"' > ~/.nanorc
echo "[+]nano config updated"

# set apt proxy
cat >> /etc/apt/apt.conf.d/02proxy <<EOL
    Acquire::http::Proxy "http://$APT_PROXY_IP:$APT_PROXY_PORT";
    Acquire::http::Proxy::ppa.launchpad.net DIRECT;
EOL

cat /etc/apt/apt.conf.d/02proxy
echo "Using host's apt proxy"

#update and upgrade via apt
echo "[i] APT Update and Upgrade in progress (can take some Time)"
apt-get -qq update &>/dev/null
apt-get -qq upgrade -y >/dev/null
echo "[i]apt update and upgrade completed"

#install additional packages
apt-get -q install $packages -y >/dev/null
echo "[+]additional packages installed"

#disable few services
systemctl disable $services &>/dev/null
echo "[-]some services disabled for autostart"

# Expand Filesystem
raspi-config --expand-rootfs &>/dev/null
echo "[i]expand rootfs in progress"
partprobe /dev/mmcblk0 &>/dev/null
echo "[i]expand rootfs ready to resize fs"
resize2fs /dev/mmcblk0p2 &>/dev/null
echo "[i]expanding rootfs finished"

# Update the firmware of your Raspberry Pi and delete all modules except the latest installed:
PRUNE_MODULES=1 rpi-update &>/dev/null

#update rc.local
sed -i '/exit/i \
#set time via ntpdate right after reboot \
ntpdate -u -b $timeserver >> /var/log/rc.local.log 2>&1 \
' /etc/rc.local
echo "[+]rc.local updated"

#update ntpdate config
sed -i '/^NTPOPTIONS/s/""/"u"/' \
/etc/default/ntpdate
echo "[+]ntpdate config updated"

#ramdisk check if exists
if [ -d /ramdisk ]; then
        echo "[!]/ramdisk exists, please check"
        exit 1 
else
        echo "[+]creating ramdisk"
fi

#create and mount ramdisk
mkdir /ramdisk
cat >> /etc/fstab <<EOF

#ramdisk
tmpfs   /ramdisk  tmpfs nodev,nosuid,size=32M  0 0
EOF
mount -a -t tmpfs
echo "[+]ramdisk created and mounted as /ramdisk"

#delete and link apt cache
rm -rf /var/cache/apt/archives
ln -s /ramdisk /var/cache/apt/archives
echo "[i]apt archive linked to ramdisk"

#persistently disable swap
swapoff --all
apt-get -q remove dphys-swapfile -y >/dev/null
echo "[-]swap disabled"

#.bashrc moficiations for root
cat >> /root/.bashrc <<EOF

#unlimited history length
HISTSIZE=
HISTFILESIZE=

#simple list alias
alias ll='ls -la --color=auto'
EOF

cat >> /home/pi/.bashrc <<EOF

#faster switch
alias s='sudo su -'
EOF
source /root/.bashrc
source /home/pi/.bashrc
echo "[i]bashrc modified"

#cleaning via apt
apt-get -q autoclean >/dev/null
apt-get -q autoremove -y >/dev/null
echo "[i]apt clean, unused packages removed"

#done, restart
shutdown -r 1 "restart in 1 min"
echo "[i]done, restart in 1 min, type shutdown -c to cancel"
